[package]
name = "test-listen"
version = "0.1.0"
authors = ["riendegris <matt@area403.org>"]
edition = "2018"

[dependencies]
tokio-postgres = "0.5"
tokio = { version = "0.2.13", features = ["full"] }
futures = "0.3"
snafu = { version = "0.6", features = [ "futures" ] }
